# Generated by Django 5.2 on 2025-05-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotnisko', '0002_lotnisko_alter_lot_destination_alter_lot_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='pasazer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='lotnisko.lot')),
            ],
        ),
    ]
