# Generated by Django 5.2 on 2025-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fisch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niem', models.CharField(max_length=64)),
                ('tlum', models.CharField(max_length=64)),
            ],
        ),
    ]
