# Generated by Django 5.2 on 2025-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fischlein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='fisch',
            name='tlum',
        ),
        migrations.AddField(
            model_name='fisch',
            name='prompt_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fisch',
            name='niem',
            field=models.CharField(max_length=256),
        ),
    ]
