# Generated by Django 5.2 on 2025-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fischlein', '0002_prompts_remove_fisch_tlum_fisch_prompt_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='opis',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='chat',
            field=models.CharField(max_length=2048),
        ),
    ]
